# Generated by Django 5.2.8 on 2026-02-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(default=True),
        ),
    ]
