# Generated by Django 5.2.8 on 2026-02-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_is_sold_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold_out',
        ),
    ]
